# This is a basic workflow to help you get started with Actions

name: ESLint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install ESLint
      run: npm install --save-dev eslint
    - name: Run ESLint
      run: npx eslint ./source/js/timer.js --ext .js -c ./.eslintrc.js
    - name: Run ESLint
      run: npx eslint ./source/js/pomodoro.js --ext .js -c ./.eslintrc.js
